apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-api
  template:
    metadata:
      labels:
        app: fcg-api
    spec:
      containers:
        - name: fcg-api
          image: 304935836160.dkr.ecr.us-east-2.amazonaws.com/fgc-api:d3ec30dcac24af1d258e57841d6ca200b39bf8d3
          ports:
            - containerPort: 80